spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: spring-ai-chatgpt-demo
  ai:
    openai:
      base-url: ${AI_BASE_URL:https://api.openai.com}
      api-key: ${AI_API_KEY:}
      chat:
        completions-path: /v1/chat/completions
        options:
          model: ${AI_MODEL:gpt-4o-mini}
          temperature: 0.7
